version: '3.8'

services:
  tracker:
    image: gszoboszlai/kia-hyundai-tracker:latest
    container_name: kia-tracker
    restart: unless-stopped
    env_file: .env
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: kia-tracker-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${KIA_DB_PASSWORD}
      MYSQL_DATABASE: ${KIA_DB_NAME}
      MYSQL_USER: ${KIA_DB_USER}
      MYSQL_PASSWORD: ${KIA_DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql_data:
